### ISSUE TITLE
请问这个报错应该怎么解决

### ISSUE THREAD

**Issue by OvO-nei** [w2r/ip_block_check#1]
[root@server ipcheck]# python ip_block_check.py
  File "ip_block_check.py", line 12
    html = f"https://api.telegram.org/bot896815847:AAFvO8_XiAbkkWBR2Jq0rv*******c/getUpdates"
                                                                                                 ^
SyntaxError: invalid syntax

看了好几遍出现这个问题 py小白 谢谢大佬

**Comment by w2r** [comment]
已沟通解决！
